// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-06-10 14:54:57.521298762 +0200 CEST m=+0.051814325

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "The API for interaction with the backend of the TuBuddy Tuberculosis Treatment Application.",
        "title": "TuBuddy API",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "paths": {}
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
