// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-06-10 15:48:20.287000084 +0200 CEST m=+0.046505064

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Test description",
        "title": "TuBuddy API",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "192.168.50:2002",
    "paths": {}
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
