# Generated by Django 2.0.5 on 2018-06-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='idd',
            new_name='id_big_database',
        ),
    ]
